#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/generate_markdown

- name: Set output_path if not defined
  set_fact:
    output_path: "{{ [ roles_dir, role_name, file_name ] | path_join | default('.') }}"
  when: output_path is not defined

- name: Generate markdown file from chosen template
  ansible.builtin.template:
    src: "{{ template_source }}"
    dest: "{{ output_path }}"